apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/ptolemaios/
images:
- name: ptolemaios
  newName: ptolemaios
  newTag: 0.0.1
patches:
- path: ./ptolemaios-dev-patch.yml