apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptolemaios
  namespace: helx
spec:
  template:
    spec:
    # Linkerd will not work with this dns policy
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

